# @package _global_

defaults:
  - _self_
  - data: gf_floodnet  # override with the dataset used for training, e.g. data=cau_flood
  - model: resnet50_resnet50
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
